# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Apara Venkateswaran
tagline:          'Personal website'
description:      ''
url:              http://aparav.github.io
baseurl:          /

author:
  name:           'Apara Venkateswaran'
  url:            https://twitter.com/apara

# Site Settings
paginate:         5
excerpt_separator: <!--excerpt_ends-->

#Plugins
whitelist:        []
gems:             [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AparaV/aparav.github.io

# Collections
collections:
    docs:
        output: true
    projects:
        output: false
